name: Build and Release Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller cloudflare-ddns

      - name: Build standalone binary
        run: |
          pyinstaller --onefile --name cloudflare_ddns.py cloudflare_ddns_synology/cli.py

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/cloudflare_ddns.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
