name: Release Synology Cloudflare DDNS Script

on:
  push:
    tags:
      - 'v*'

jobs:
  release-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload Release Asset (Raw Script)
        uses: softprops/action-gh-release@v2
        with:
          files: cloudflare_ddns_synology/cli.py
          name: cloudflare_ddns.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
